name: 'Check'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/bot/**'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'push'
    uses: SlashNephy/.github/.github/workflows/go-run.yml@master
    permissions:
      contents: 'read'
    with:
      task: 'build'
      working-directory: 'packages/bot'

  lint:
    uses: SlashNephy/.github/.github/workflows/go-lint.yml@master
    permissions:
      contents: 'read'
      pull-requests: 'write'
    with:
      working-directory: 'packages/bot'
